### ISSUE TITLE
Enable optimization when building

### ISSUE THREAD

**Issue by GoD-Tony** [peace-maker/sourcetvmanager#1]
A quick note to make sure `--enable-optimize` is used when building. Some of the bins in the release look quite big. (csgo.dll/.so 1mb/6mb, css.so 512kb, etc)

**Comment by peace-maker** [comment]
You're right, thanks. I've done `python ../configure.py -s present --enable-optimize`. Looks like it's required to be set before specifying the sdks.

**Comment by peace-maker** [comment]
Spoke too soon. Even the other way around the binaries are the same size.
