### ISSUE TITLE
Error: Could not find interface: IPlayerManager

### ISSUE THREAD

**Issue by drixevel-dev** [peace-maker/sourcetvmanager#26]
`<FAILED> file "sourcetvmanager.ext.2.hl2dm.dll": Could not find interface: IPlayerManager`

Running the latest copy of Sourcemod 1.11.0.6926 on Windows and I downloaded it from the latest build from 3 months ago.

**Comment by peace-maker** [comment]
The `-smlatest` build is built against SourceMod 1.12, which had an interface bump and thus prevents the extension to load on older sourcemod versions. I've included SourceMod 1.11 in the CI build matrix now, so please try that build once it finishes.

**Comment by drixevel-dev** [comment]
Solved, thank you kindly.
