### ISSUE TITLE
Gamedata outdated(?)

### ISSUE THREAD

**Issue by Bara20** [peace-maker/sourcetvmanager#3]
Since latest csgo update: https://crash.limetech.org/hcswjg472rws

**Comment by RussianRonin** [comment]
I am also having similar issues!

https://crash.limetech.org/jkvhhjcqdy6g

**Comment by peace-maker** [comment]
Could you check out the new gamedata please?

**Comment by Bara20** [comment]
Doesn't work ( https://github.com/peace-maker/sourcetvmanager/commit/f11a9b22635eb1850f8b37ccaae2e8729bae9ce4 ).
https://crash.limetech.org/evztjimaiplb

**Comment by peace-maker** [comment]
It's tested this time.

**Comment by Bara20** [comment]
Works again 👍 Ty
