### ISSUE TITLE
forward void SourceTV_OnSpectatorChatMessage_Post Doesn't work in Left 4 Dead 2

### ISSUE THREAD

**Issue by endelei** [peace-maker/sourcetvmanager#36]
forward Action SourceTV_OnSpectatorChatMessage
forward void SourceTV_OnSpectatorChatMessage_Post
Doesn't work in Left 4 Dead 2,
Other forward and native are available,
version:sourcetvmanager-sm1.11-win-2c3d68e
version:sourcetvsupport-sm1.11-win-0222e04

**Comment by A1mDev** [comment]
Problem solved in PR #37
